# Generated by Django 4.0.6 on 2022-07-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pref',
            field=models.BooleanField(default=False),
        ),
    ]
